apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 2
    maxSize: 5
    minSize: 1
    scalingConfig:
      desiredSize: 2
      maxSize: 5
      minSize: 1
      labels:
        environment: production
        role: backend
      tags:
        environment: production
        project: my-project
