version: '3'

services:
  jenkins-blueocean:
    image: myjenkins-blueocean:2.426.3-1
    container_name: jenkins-blueocean
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    #  - DOCKER_HOST=tcp://docker:2376
    #  - DOCKER_CERT_PATH=/certs/client
    #  - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    #  - jenkins-docker-certs:/certs/client:ro
    user: "1000:999"

networks:
  jenkins:

volumes:
  jenkins-data:
#  jenkins-docker-certs: